server:
  port: 8082
  servlet:
    context-path: /business

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/train_business?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: train_business
    password: business
    driver-class-name: com.mysql.cj.jdbc.Driver
  mybatis:
    configuration:
      map-underscore-to-camel-case: true # 可选项，开启下划线转驼峰命名规则
    #    type-aliases-package: com.example.yourpackage.entity # 实体类所在的包路径
    mapper-locations: classpath*:mapper/**/*.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl