server:
  port: 8099

spring:
  application:
    name: timer
  datasource:
    url: jdbc:mysql://localhost:3306/train_timer?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: train_timer
    password: train_timer
    driver-class-name: com.mysql.cj.jdbc.Driver